mat = {'Rizma Yudatama':['Ganteng/Cantik', 'Tinggi', 'Pemalu', 'Supel', 'Ramah', 'Aktif', 'Jujur', 'Ingin tau', 'Pintar',
                'Dewasa', 'Lembut', 'Kalem', 'Mageran', 'Santuy', 'Rapi', 'Ngantukan', 'Gajelas', 'Akhi/ukhti', 'Tinggi', 'Suami/istriable'],
        'Intan a s':['Pemalu', 'Supel', 'Ramah', 'Jujur', 'Ingin tau', 'Lucu', 'Barbar', 'Berisik', 'Silent reader',
                'Peka', 'Lemot', 'Mageran', 'Ngantukan', 'Gajelas', 'Rempong', 'Extrovert', 'Tembem'],
        'Elfadea':['Ribet'],
        'Tsr':['Manis', 'Pemalu', 'Ramah', 'Jujur', 'Ingin tau', 'Lembut', 'Kalem', 'Silent reader', 'Peka', 'Lemot', 'Santuy',
                'Rapi', 'Ngantukan'],
        'Nurul Aulia':['Manis', 'Supel', 'Ramah', 'Aktif', 'Percaya diri', 'Jujur', 'Dewasa', 'Lembut', 'Peka',
                'Kreatif', 'Santuy', 'Suami/istriable', 'Tembem'],
        'Javas Alfreda Belva Yoga Pratama':['Manis', 'Introvert', 'Pemalu', 'Supel', 'Ramah', 'Aktif', 'Ganteng/Cantik',
                'Percaya diri', 'Jujur', 'Ingin tau', 'Pintar', 'Tegas', 'Dewasa', 'Lucu', 'Lembut', 'Barbar', 'Berisik', 'Kalem', 'Medok',
                'Silent reader', 'Peka', 'Kreatif', 'Lemot', 'Mageran', 'Suka telat', 'Santuy', 'Rapi', 'Ngantukan', 'Gajelas', 'Ribet', 'Rempong',
                'Suka gosip', 'Akhi/ukhti', 'Tinggi', 'Suami/istriable', 'Extrovert', 'Tembem', 'Sipit'],
        'Zuppa soup':['Supel', 'Percaya diri', 'Lucu', 'Berisik', 'Silent reader', 'Peka', 'Kreatif', 'Suka telat', 'Santuy', 'Ngantukan', 'Rempong',
                'Extrovert', 'Tembem'],
        'Dwi Alifah Nurcahyani':['Supel', 'Ramah', 'Aktif', 'Ganteng/Cantik', 'Percaya diri', 'Jujur', 'Dewasa', 'Lucu', 'Barbar', 'Berisik', 'Medok',
                'Peka', 'Lemot', 'Mageran', 'Santuy', 'Rapi', 'Ngantukan', 'Gajelas', 'Ribet', 'Rempong', 'Suka gosip', 'Tinggi', 'Suami/istriable', 'Tembem'],
        'Syahida Amalia Rosyada':['Ramah', 'Ganteng/Cantik', 'Jujur', 'Ingin tau', 'Lucu', 'Berisik', 'Peka', 'Suka telat', 'Ngantukan', 'Suka gosip'],
        'Calon Orang Sukses Dunia Akhirat':['Manis', 'Supel', 'Ramah', 'Aktif', 'Ganteng/Cantik', 'Percaya diri', 'Jujur', 'Ingin tau', 'Lucu', 'Lembut',
                'Berisik', 'Kalem', 'Medok', 'Peka', 'Lemot', 'Mageran', 'Suka telat', 'Santuy', 'Rapi', 'Ngantukan', 'Gajelas', 'Ribet', 'Rempong', 'Suka gosip',
                'Suami/istriable', 'Tembem', 'Sipit'],
        'Ayu Kumala Dewi':['Manis', 'Supel', 'Aktif', 'Ganteng/Cantik', 'Percaya diri', 'Ingin tau', 'Tegas', 'Lucu', 'Barbar', 'Berisik', 'Peka', 'Kreatif', 'Mageran', 'Santuy',
                'Rapi', 'Suami/istriable', 'Extrovert'],
        'Zahraaaaaaaaa.':['Introvert', 'Pemalu', 'Percaya diri', 'Jujur', 'Barbar', 'Berisik', 'Kalem', 'Silent reader', 'Lemot', 'Mageran', 'Santuy', 'Gajelas', 'Akhi/ukhti', 'Tinggi', 'Extrovert'],
        'celline':['Ganteng/Cantik', 'Gajelas'],
        'Defita Rani Utami':['Introvert', 'Ramah', 'Jujur', 'Mageran', 'Tinggi'],
        'Oioioi':['Manis', 'Introvert', 'Pemalu', 'Supel', 'Ramah', 'Aktif', 'Ganteng/Cantik', 'Percaya diri', 'Jujur', 'Ingin tau', 'Pintar', 'Tegas', 'Dewasa', 'Lucu', 'Lembut',
                'Barbar', 'Berisik', 'Kalem', 'Medok', 'Silent reader', 'Peka', 'Kreatif', 'Lemot', 'Mageran', 'Suka telat', 'Santuy', 'Rapi', 'Ngantukan', 'Gajelas', 'Ribet',
                'Rempong', 'Suka gosip', 'Akhi/ukhti', 'Tinggi', 'Suami/istriable', 'Extrovert', 'Tembem', 'Sipit'],
        'Devi Eka P':['Berisik', 'Ribet', 'Tembem'],
        'ASMI DWI ATNASARI':['Introvert', 'Jujur', 'Kalem', 'Silent reader', 'Peka', 'Kreatif', 'Lemot', 'Tinggi', 'Tembem'],
        'Rama A P':['Introvert', 'Pemalu', 'Ramah', 'Jujur', 'Ingin tau', 'Kalem', 'Silent reader', 'Mageran', 'Santuy', 'Rapi', 'Gajelas'],
        'Neli Nurhayati':['Introvert', 'Pemalu', 'Supel', 'Ramah', 'Jujur', 'Ingin tau', 'Lembut', 'Kalem', 'Peka', 'Santuy', 'Gajelas',
                'Ribet', 'Tinggi', 'Aneh'],
        'Afif Miftahudi':['Pemalu', 'Ramah', 'Aktif', 'Ganteng/Cantik', 'Percaya diri', 'Jujur', 'Ingin tau', 'Tegas', 'Lucu', 'Lembut', 'Berisik', 'Peka',
                'Kreatif', 'Lemot', 'Mageran', 'Santuy', 'Gajelas', 'Tinggi', 'Suami/istriable']
        }

pertanyaan = [
    ['Apakah dia Manis?','Manis'],
    ['Apakah dia Introvert?','Introvert'],
    ['Apakah dia Pemalu?','Pemalu'],
    ['Apakah dia Supel?','Supel'],
    ['Apakah dia Ramah?','Ramah'],
    ['Apakah dia Aktif?','Aktif'],
    ['Apakah dia Ganteng/Cantik?','Ganteng/Cantik'],
    ['Apakah dia Percaya diri?','Percaya diri'],
    ['Apakah dia Jujur?','Jujur'],
    ['Apakah dia Ingin tau?','Ingin tau'],
    ['Apakah dia Pintar?','Pintar'],
    ['Apakah dia Tegas?','Tegas'],
    ['Apakah dia Dewasa?','Dewasa'],
    ['Apakah dia Lucu?','Lucu'],
    ['Apakah dia Lembut?','Lembut'],
    ['Apakah dia Barbar?','Barbar'],
    ['Apakah dia Berisik?','Berisik'],
    ['Apakah dia Kalem?','Kalem'],
    ['Apakah dia Medok?','Medok'],
    ['Apakah dia Silent reader?','Silent reader'],
    ['Apakah dia Peka?','Peka'],
    ['Apakah dia Kreatif?','Kreatif'],
    ['Apakah dia Lemot?','Lemot'],
    ['Apakah dia Mageran?','Mageran'],
    ['Apakah dia Suka telat?','Suka telat'],
    ['Apakah dia Santuy?','Santuy'],
    ['Apakah dia Rapi?','Rapi'],
    ['Apakah dia Ngantukan?','Ngantukan'],
    ['Apakah dia Gajelas?','Gajelas'],
    ['Apakah dia Ribet?','Ribet'],
    ['Apakah dia Rempong?','Rempong'],
    ['Apakah dia Suka gosip?','Suka gosip'],
    ['Apakah dia Akhi/ukhti?','Akhi/ukhti'],
    ['Apakah dia Tinggi?','Tinggi'],
    ['Apakah dia Suami/istriable?','Suami/istriable'],
    ['Apakah dia Extrovert?','Extrovert'],
    ['Apakah dia Tembem?','Tembem'],
    ['Apakah dia Sipit?','Sipit']
    ]

span = []
for i in range(0, (len(pertanyaan)-1)):
    span.append(i)

index = span