# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['mathkinator.py'],
             pathex=['D:\\Python Project\\Mathkinator'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['altgraph==0.17',
                'beautifulsoup4==4.8.2',
                'brute==0.0.3',
                'bruter==0.0.2',
                'bs4==0.0.1',
                'certifi==2019.11.28',
                'chardet==3.0.4',
                'colorama==0.4.3',
                'colour==0.1.5',
                'cycler==0.10.0',
                'DateTime==4.3',
                'demjson==2.2.4',
                'future==0.18.2',
                'graph-theory==2020.2.14.44994',
                'idna==2.9',
                'instaloader==4.2.10',
                'kiwisolver==1.1.0',
                'lib==3.0.0',
                'lxml==4.5.0',
                'matplotlib==3.2.0',
                'more-itertools==8.2.0',
                'nose==1.3.7',
                'numpy==1.18.1',
                'opencv-python==4.2.0.32',
                'pandas==1.0.1',
                'pefile==2019.4.18',
                'Pillow==7.0.0',
                'pycairo==1.19.0',
                'pydub==0.23.1',
                'pyparsing==2.4.6',
                'pyreadline==2.1',
                'python-dateutil==2.8.1',
                'pytz==2019.3',
                'pywin32-ctypes==0.2.0',
                'requests==2.23.0',
                'scipy==1.4.1',
                'six==1.14.0',
                'soupsieve==2.0',
                'tabulate==0.8.6',
                'tqdm==4.42.1',
                'urllib3==1.25.8',
                'xlrd==1.2.0',
                'xmltodict==0.12.0',
                'youtube-dl==2020.3.8',
                'zope.interface'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='mathkinator',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
